"""Константы для приложения bot_management."""

BOT_NAME_LENGTH = 255
ACTION_NAME_LENGTH = 20
DESCRIPTION_LENGTH = 1000
MESSAGE_LENGTH = 1000
MIN_LETTERS = 3
API_KEY_LENGTH = 255
API_URL_LENGTH = 255
MAX_POSITIONS = 30
