"""Константы для приложения bot_management."""

BOT_NAME_LENGTH = 255
ACTION_NAME_LENGTH = 20
TELEGRAM_TOKEN_LENGTH = 46
DESCRIPTION_LENGTH = 1000
MESSAGE_LENGTH = 1000
API_KEY_LENGTH = 255
API_URL_LENGTH = 255
MAX_POSITIONS = 30
ACTION_TYPE_LENGTH = 30
METHOD_LENGTH = 7
VARIABLE_LENGTH = 30
MIN_TELEGRAM_ID_LENGTH = 8
MAX_TELEGRAM_ID_LENGTH = 10
TELEGRAM_TOKEN_KEY_LENGTH = 35
COMMAND_KEYWORD_LENGTH = 32
HEADER_LENGTH = 30
VARIABLE_TYPE_LENGTH = 15
