# Generated by Django 5.0.6 on 2024-06-13 12:27

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="telegrambot",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("name"), name="unique_name"
            ),
        ),
    ]
