# Generated by Django 5.0.4 on 2024-04-14 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="telegrambot",
            old_name="api_availablility",
            new_name="api_availability",
        ),
    ]
