# Generated by Django 5.0.6 on 2024-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0002_alter_header_options_alter_variable_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambotaction",
            name="message",
            field=models.CharField(
                blank=True, max_length=1000, null=True, verbose_name="Текст сообщения"
            ),
        ),
    ]
