# Generated by Django 5.0.4 on 2024-04-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bot_management",
            "0002_rename_api_availablility_telegrambot_api_availability",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambot",
            name="description",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Описание бота"
            ),
        ),
        migrations.AddField(
            model_name="telegrambotaction",
            name="api_key",
            field=models.CharField(blank=True, max_length=255, verbose_name="Ключ API"),
        ),
        migrations.AddField(
            model_name="telegrambotaction",
            name="api_url",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Адрес API"
            ),
        ),
        migrations.AddField(
            model_name="telegrambotaction",
            name="description",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Описание действия"
            ),
        ),
        migrations.AlterField(
            model_name="telegrambotaction",
            name="message",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Текст сообщения"
            ),
        ),
    ]
