# Generated by Django 5.0.6 on 2024-06-04 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0003_alter_telegrambotaction_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variable",
            name="telegram_action",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variables",
                to="bot_management.telegrambotaction",
            ),
        ),
    ]
