# Generated by Django 5.0.4 on 2024-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bot_management",
            "0003_telegrambot_description_telegrambotaction_api_key_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambot",
            name="api_key",
            field=models.CharField(blank=True, max_length=255, verbose_name="Ключ API"),
        ),
        migrations.AlterField(
            model_name="telegrambot",
            name="api_url",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Адрес API"
            ),
        ),
    ]
