# Generated by Django 5.0.6 on 2024-06-05 09:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0004_alter_variable_telegram_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambotaction",
            name="position",
            field=models.SmallIntegerField(
                blank=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="Номер действия",
            ),
        ),
        migrations.AlterField(
            model_name="variable",
            name="telegram_action",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variables",
                to="bot_management.telegrambotaction",
            ),
            preserve_default=False,
        ),
    ]
