# Generated by Django 5.0.6 on 2024-06-05 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0005_alter_telegrambotaction_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambotaction",
            name="position",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="Номер действия",
            ),
        ),
    ]
