# Generated by Django 5.0.4 on 2024-04-24 16:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0005_alter_telegrambot_api_key_alter_telegrambot_api_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambot",
            name="api_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="Адрес API"),
        ),
        migrations.AlterField(
            model_name="telegrambot",
            name="name",
            field=models.CharField(
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^[a-zA-Zа-яёА-ЯЁ]{3}[\\w\\W]{0,251}\\S$"
                    )
                ],
                verbose_name="Название бота",
            ),
        ),
        migrations.AlterField(
            model_name="telegrambot",
            name="telegram_token",
            field=models.CharField(
                max_length=45,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^[0-9]{8,10}:[a-zA-Z0-9_-]{35}$"
                    )
                ],
                verbose_name="Токен авторизации телеграм бота",
            ),
        ),
        migrations.AlterField(
            model_name="telegrambotaction",
            name="api_url",
            field=models.URLField(blank=True, max_length=255, verbose_name="Адрес API"),
        ),
        migrations.AlterField(
            model_name="telegrambotaction",
            name="command_keyword",
            field=models.CharField(
                help_text="команда должна начинаться с / и содержать только латинские буквы, цифры и нижнее подчеркивание _, макс. длина 32 символа",
                max_length=33,
                validators=[
                    django.core.validators.RegexValidator(regex="^/[a-zA-Z0-9_]{1,32}$")
                ],
                verbose_name="Текст команды",
            ),
        ),
        migrations.AlterField(
            model_name="telegrambotaction",
            name="name",
            field=models.CharField(
                help_text="только латинские буквы и цифры, от 3 до 20 символов.",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^[a-zA-Zа-яёА-ЯЁ]{3}[\\w\\W]{0,16}\\S$"
                    )
                ],
                verbose_name="Название действия",
            ),
        ),
        migrations.AlterField(
            model_name="telegrambotaction",
            name="next_action",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_action",
                to="bot_management.telegrambotaction",
            ),
        ),
        migrations.AlterField(
            model_name="telegrambotaction",
            name="position",
            field=models.SmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(30),
                ],
                verbose_name="Номер действия",
            ),
        ),
    ]
