# Generated by Django 5.0.4 on 2024-04-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "bot_management",
            "0006_alter_telegrambot_api_url_alter_telegrambot_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambotaction",
            name="next_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_actions",
                to="bot_management.telegrambotaction",
            ),
        ),
    ]
