# Generated by Django 5.0.4 on 2024-05-04 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0007_alter_telegrambotaction_next_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambot",
            name="telegram_token",
            field=models.CharField(
                max_length=46,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex="^[0-9]{8,10}:[a-zA-Z0-9_-]{35}$"
                    )
                ],
                verbose_name="Токен авторизации телеграм бота",
            ),
        ),
    ]
