# Generated by Django 5.0.4 on 2024-05-05 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0008_alter_telegrambot_telegram_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambot",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название бота"),
        ),
        migrations.AlterField(
            model_name="telegrambotaction",
            name="name",
            field=models.CharField(max_length=20, verbose_name="Название действия"),
        ),
    ]
