# Generated by Django 5.0.4 on 2024-05-22 12:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0009_alter_telegrambot_name_alter_telegrambotaction_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegrambotaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("MESSAGE", "Сообщение"),
                    ("QUERY", "Запрос к пользователю"),
                    ("HTTP_REQUEST", "Http запрос"),
                ],
                default="MESSAGE",
                max_length=30,
                verbose_name="Тип действия",
            ),
        ),
        migrations.AddField(
            model_name="telegrambotaction",
            name="api_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GET", "Get запрос"),
                    ("POST", "Post запрос"),
                    ("PATCH", "Patch запрос"),
                    ("DELETE", "Delete запрос"),
                    ("PUT", "Put запрос"),
                ],
                default="GET",
                max_length=7,
                verbose_name="Метод запроса к API",
            ),
        ),
        migrations.AddField(
            model_name="telegrambotaction",
            name="data",
            field=models.JSONField(blank=True, null=True, verbose_name="Данные"),
        ),
        migrations.AlterField(
            model_name="telegrambotaction",
            name="command_keyword",
            field=models.CharField(
                blank=True,
                help_text="команда должна начинаться с / и содержать только латинские буквы, цифры и нижнее подчеркивание _, макс. длина 32 символа",
                max_length=33,
                validators=[
                    django.core.validators.RegexValidator(regex="^/[a-zA-Z0-9_]{1,32}$")
                ],
                verbose_name="Текст команды",
            ),
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="[a-zA-Z0-9-]{1,30}"
                            )
                        ],
                        verbose_name="Наименование заголовка",
                    ),
                ),
                (
                    "telegram_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="headers",
                        to="bot_management.telegrambotaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Variable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="В названии используйте только латинские буквы и цифры, _ и -",
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                regex="^[a-zA-Z0-9_]{1,30}"
                            )
                        ],
                        verbose_name="Название переменной",
                    ),
                ),
                (
                    "variable_type",
                    models.CharField(
                        choices=[
                            ("INT", "Целое число"),
                            ("FLOAT", "Число с плавающей запятой"),
                            ("STRING", "Строка"),
                        ],
                        max_length=15,
                        verbose_name="Тип переменной",
                    ),
                ),
                (
                    "telegram_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variables",
                        to="bot_management.telegrambotaction",
                    ),
                ),
            ],
        ),
    ]
