# Generated by Django 5.0.4 on 2024-05-24 10:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0010_telegrambotaction_action_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambot",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="telegrambot",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название бота"
            ),
        ),
    ]
