# Generated by Django 5.0.6 on 2024-05-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bot_management", "0011_alter_telegrambot_created_at_alter_telegrambot_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambotaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("MESSAGE", "Сообщение"),
                    ("QUERY", "Запрос к пользователю"),
                    ("HTTP_REQUEST", "Http запрос"),
                    ("GetListHandler", "Получение Списка"),
                    ("StopHandler", "Остановка"),
                    ("Handlers", "Старт"),
                    ("SendMassage", "Получение обьекта"),
                ],
                default="MESSAGE",
                max_length=30,
                verbose_name="Тип действия",
            ),
        ),
    ]
