version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes: [pg_data:/var/lib/postgresql/data]
    restart: always

  bot_server:
    build: ./bot_server/
    env_file: .env
    ports: [8001:8080]
    depends_on: [db]

  bot_constructor:
    build: ./bot_constructor/
    env_file: .env
    ports: [8002:8000]
    depends_on: [db]

  gateway:
    build: ./gateway/
    env_file: .env
    ports: [80:80]
    depends_on: [bot_constructor]
    volumes: [static:/staticfiles/, media:/app/media/]
