version: '3.8'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes: [pg_data:/var/lib/postgresql/data]
    restart: always
    networks: [my_network]

  bot_server:
    build: ./bot_server/
    env_file: .env
    ports: [8080:8080]
    depends_on: [db]
    networks: [my_network]

  bot_constructor:
    build: ./bot_constructor/
    env_file: .env
    ports: [8002:8002]
    depends_on: [db]
    networks: [my_network]

  gateway:
    build: ./gateway/
    env_file: .env
    ports: [8000:80]
    depends_on: [bot_constructor]
    volumes: [static:/staticfiles/, media:/app/media/]
    networks: [my_network]

networks:
  my_network:
    driver: bridge