version: '3'
services:
  nginx:
    image: nginxdemos/hello:0.4
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik

  postgres:
    image: postgres:16.1-alpine
    env_file: stack.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik

  pgadmin:
    image: dpage/pgadmin4:8.6
    depends_on:
      postgres:
    env_file: stack.env
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - traefik

volumes:
  postgres_data:
  pgadmin_data:

networks:
  traefik:
    external: true
