@baseUrl = https://dev.xwick.ru/v1
@authToken = {{tokenAPI.response.headers.Set-Cookie}}

###
# @name tokenAPI
POST {{baseUrl}}/users/login/
Content-Type: application/json
# Authorization: Bearer {{authToken}}

{
  "email": "6509588@mail.ru",
  "password": "!234qwer"
}

### Get my user profile
GET {{baseUrl}}/users/login
Content-Type: application/json
# Authorization: Bearer {{authToken}}

###
HTTP/1.1 200 OK
Allow: OPTIONS, POST, GET
Content-Length: 27
Content-Type: application/json
Cross-Origin-Opener-Policy: same-origin
Date: Thu, 13 Jun 2024 14:13:39 GMT
Referrer-Policy: same-origin
Server: gunicorn
Set-Cookie: csrftoken=HGaxeupnX28HHJQH81sVzJjTEVxBDHtH; expires=Thu, 12 Jun 2025 14:13:39 GMT; Max-Age=31449600; Path=/; SameSite=None; Secure,X-CSRFToken=4klpoiihkb0nd1rjgyicpx60chaqhlqt; expires=Thu, 27 Jun 2024 14:13:39 GMT; HttpOnly; Max-Age=1209600; Path=/; SameSite=Lax
Vary: Accept, Cookie, origin
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
Connection: close

{
  "email": "6509588@mail.ru"
}
