version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgresdb"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "456852"
    ports:
      - "5432:5432"
