## DYNAMIC configuration
## path to place the file
## scp infra/traefik/external/services.yml sihuan@xwick.ru:/home/sihuan/modular/dockume/traefik/external
## path to place usersfile
## scp infra/traefik/external/usersfile sihuan@xwick.ru:/home/sihuan/modular/dockume/traefik/external
## https://bcrypt-generator.com/

http:
  routers:
    to-nginx:
      entryPoints:
        - web
        - websecure
      rule: Host(`xwick.ru`)
      tls:
        certResolver: letsencrypt
        # domains:
        #   - main: "xwick.ru"
        #     sans:
        #       - "*.xwick.ru"
      service: nginx

    to-botconstructor:
      entryPoints:
        - websecure
      rule: Host(`api.xwick.ru`)
      tls:
        certResolver: letsencrypt
      service: botconstructor

    to-devconstructor:
      entryPoints:
        - websecure
      rule: Host(`dev.xwick.ru`)
      tls:
        certResolver: letsencrypt
      service: devconstructor

    to-botserver:
      entryPoints:
        - websecure
      rule: Host(`api.xwick.ru`) && PathPrefix(`/botserver`)
      tls:
        certResolver: letsencrypt
      service: botserver

    to-testingapp:
      entryPoints:
        - websecure
      rule: Host(`api.xwick.ru`) && PathPrefix(`/testingapp`)
      tls:
        certResolver: letsencrypt
      service: testingapp

    to-traefik:
      entryPoints:
        - websecure
      rule: Host(`traefik.xwick.ru`)
      middlewares:
        - auth
      tls:
        certResolver: letsencrypt
      service: traefik

    to-pgadmin:
      entryPoints:
        - websecure
      rule: Host(`pgadmin.xwick.ru`)
      middlewares:
        - auth
      tls:
        certResolver: letsencrypt
      service: pgadmin

  middlewares:
    auth:
      basicAuth:
        usersFile: /external/usersfile

  services:
    nginx:
      loadBalancer:
        servers:
        - url: http://nginx:80

    botconstructor:
      loadBalancer:
        servers:
        - url: http://botconstructor:8000

    devconstructor:
      loadBalancer:
        servers:
        - url: http://devconstructor:8000

    botserver:
      loadBalancer:
        servers:
        - url: http://botserver:8080

    testingapp:
      loadBalancer:
        servers:
        - url: http://testing:8080

    pgadmin:
      loadBalancer:
        servers:
        - url: http://pgadmin:80

    traefik:
      loadBalancer:
        servers:
        - url: http://proxy-server:8080