## DYNAMIC configuration
## path to place the file
## scp infra/traefik/external/services.yml sihuan@xwick.ru:/home/sihuan/modular/dockume/traefik/external
## path to place usersfile
## scp infra/traefik/external/usersfile sihuan@xwick.ru:/home/sihuan/modular/dockume/traefik/external
## https://bcrypt-generator.com/

http:
  routers:
    to-frontend:
      entryPoints:
        - web
        - websecure
      rule: Host(`xwick.ru`)
      service: frontend

    to-botconstructor:
      entryPoints:
        - websecure
      rule: Host(`api.xwick.ru`) || (Host(`xwick.ru`) && PathPrefix(`/undefined`))
      middlewares:
        - stripUndefined
      service: botconstructor

    to-devconstructor:
      entryPoints:
        - websecure
      rule: Host(`dev.xwick.ru`)
      service: devconstructor

    to-botserver:
      entryPoints:
        - websecure
      rule: Host(`bsrv.xwick.ru`)
      service: botserver

    to-testingapp:
      entryPoints:
        - websecure
      rule: Host(`tapp.xwick.ru`)
      service: testingapp

    to-traefik:
      entryPoints:
        - websecure
      rule: Host(`traefik.xwick.ru`)
      middlewares:
        - auth
      service: traefik

    to-pgadmin:
      entryPoints:
        - websecure
      rule: Host(`pgadmin.xwick.ru`)
      middlewares:
        - auth
      service: pgadmin

  middlewares:
    www-remover:
      redirectRegex:
        regex: ^https://www\.(.*)
        replacement: https://$1
    stripUndefined:
      stripPrefix:
        prefixes:
          - "/undefined"
    auth:
      basicAuth:
        usersFile: /external/usersfile
    secureHeaders:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        frameDeny: true
        browserXssFilter: true
        contentTypeNosniff: true

  services:
    frontend:
      loadBalancer:
        servers:
        - url: http://frontend:8080

    botconstructor:
      loadBalancer:
        servers:
        - url: http://botconstructor:8000

    devconstructor:
      loadBalancer:
        servers:
        - url: http://devconstructor:8000

    botserver:
      loadBalancer:
        servers:
        - url: http://botserver:8080

    testingapp:
      loadBalancer:
        servers:
        - url: http://testingapp:8080

    pgadmin:
      loadBalancer:
        servers:
        - url: http://pgadmin:80

    traefik:
      loadBalancer:
        servers:
        - url: http://proxy-server:8080