version: "3"

services:
  fief-server:
    container_name: fief-server
    image: ghcr.io/fief-dev/fief:0.28.6
    command: fief run-server --port 8000
    env_file: stack.env
    depends_on:
      - postgres
      - redis
    networks:
      - traefik

  worker:
    # container_name: fief-worker
    image: ghcr.io/fief-dev/fief:0.28.6
    command: fief run-worker -p 1 -t 1
    env_file: stack.env
    networks:
      - traefik

  postgres:
    # container_name: fief_postgres
    image: postgres:16.1-alpine
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
    env_file: stack.env
    healthcheck:
      interval: 10s
      retries: 10
      test: "pg_isready -U \"${POSTGRES_USER}\" -d \"${POSTGRES_DB}\""
      timeout: 2s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - traefik

  redis:
    # container_name: fief_redis
    image: redis:alpine
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - traefik

volumes:
  redis_data:
  postgres_data:

networks:
  traefik:
    external: true
