## STATIC configuration
## path to place the file
## scp infra/traefik/config/traefik.yml sihuan@xwick.ru:/home/sihuan/modular/dockume/traefik/config

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: :443
  botserver:
    address: :8081

api:
  dashboard: true
  insecure: true

providers:
  docker:
    network: traefik
    exposedByDefault: false
  file:
    directory: /external
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: sihuannewrise@gmail.com
      storage: /letsencrypt/acme.json
      # for use during development
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

accesslog: true

# log:
#   level: DEBUG
