## STATIC configuration
## path to place the file
## scp MODULAR/config/traefik.yml sihuan@xwick.ru:/home/sihuan/modular/dockume/traefik/config
## scp MODULAR/config/traefik.yml sihuan@80.87.105.197:/home/sihuan/modular/dockume/traefik/config

entryPoints:
  # ssh:
  #   address: ":22"
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
  websecure:
    address: ":443"
  # postgresql:
  #   address: ":5432"
  # fief:
  #   address: ":8000"

api:
  dashboard: true
  insecure: true

providers:
  docker:
    network: traefik
    exposedByDefault: false
  file:
    directory: /external
    watch: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: sihuannewrise@gmail.com
      storage: /letsencrypt/acme.json
      # caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

accesslog: true

# log:
#   level: DEBUG
