# Generated by Django 5.0.4 on 2024-04-22 19:05

import bot_constructor.apps.bot_management.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramBot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название бота"),
                ),
                (
                    "telegram_token",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Токен авторизации телеграм бота",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Описание бота"
                    ),
                ),
                ("api_key", models.CharField(max_length=255, verbose_name="Ключ API")),
                ("api_url", models.CharField(max_length=255, verbose_name="Адрес API")),
                (
                    "api_availability",
                    models.BooleanField(
                        blank=True, default=False, verbose_name="Доступность API"
                    ),
                ),
                (
                    "is_started",
                    models.BooleanField(default=False, verbose_name="Запущен"),
                ),
                (
                    "bot_state",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("RUNNING", "Запущен"),
                            ("STOPPED", "Остановлен"),
                            ("ERROR", "Ошибка"),
                        ],
                        default="DRAFT",
                        max_length=7,
                        verbose_name="Статус бота",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата последнего запуска бота",
                    ),
                ),
            ],
            options={
                "verbose_name": "Телеграм бот",
                "verbose_name_plural": "Телеграм боты",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="TelegramBotAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="только латинские буквы и цифры, от 3 до 20 символов.",
                        max_length=20,
                        verbose_name="Название действия",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Описание действия"
                    ),
                ),
                (
                    "command_keyword",
                    models.CharField(
                        help_text="команда должна начинаться с / и содержать только латинские буквы, цифры и нижнее подчеркивание _, макс. длина 32 символа",
                        max_length=33,
                        verbose_name="Текст команды",
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="Текст сообщения"
                    ),
                ),
                (
                    "api_url",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Адрес API"
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ключ API"
                    ),
                ),
                ("position", models.SmallIntegerField(verbose_name="Номер действия")),
                ("is_active", models.BooleanField(verbose_name="Вкл/выкл")),
                (
                    "telegram_bot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="bot_constructor.telegrambot",
                        verbose_name="Телеграм бот",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие",
                "verbose_name_plural": "Действия",
                "unique_together": {("telegram_bot", "position")},
            },
        ),
        migrations.CreateModel(
            name="TelegramBotFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=bot_constructor.apps.bot_management.models.bot_directory_path,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "telegram_action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="bot_constructor.telegrambotaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
            },
        ),
    ]
