---
name: bot-server CICD
run-name: ${{ github.actor }} started 🚀 GitHub Actions
on:
  push:
    branches: [feat/container-for-bot-server]
    paths-ignore: ['**/pyproject.toml']
  workflow_dispatch:
env:
  APP_VERSION: bs1.0.1
  APP_IMAGE_NAME: bot_server
  APP_CONTAINER_NAME: bot_server
jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./${{env.APP_IMAGE_NAME}}
          file: ${{env.APP_IMAGE_NAME}}/Dockerfile
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/${{env.APP_IMAGE_NAME}}:latest
            ${{secrets.DOCKERHUB_USERNAME}}/${{env.APP_IMAGE_NAME}}:${{env.APP_VERSION}}
  deploy:
    name: Deployment on remote server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.MODULAR_HOST}}
          username: ${{secrets.HOST_USER}}
          key: ${{secrets.HOST_SSH_KEY}}
          script: |
            docker stop ${{env.APP_CONTAINER_NAME}}
            docker rm ${{env.APP_CONTAINER_NAME}}
            docker rmi ${{secrets.DOCKERHUB_USERNAME}}/${{env.APP_IMAGE_NAME}}:latest
            docker pull ${{secrets.DOCKERHUB_USERNAME}}/${{env.APP_IMAGE_NAME}}:latest
            docker run -d \
              --name=${{env.APP_CONTAINER_NAME}} \
              --hostname=${{env.APP_CONTAINER_NAME}} \
              --net=${{secrets.MODULAR_NETWORK_NAME}} \
              --restart=unless-stopped \
              -e POSTGRES_DB=${{secrets.DJANGO_DB_NAME}} \
              -e POSTGRES_USER=${{secrets.DJANGO_POSTGRES_USER}} \
              -e POSTGRES_PASSWORD=${{secrets.DJANGO_POSTGRES_PASSWORD}} \
              -e DB_HOST='postgres' \
              -e DB_PORT=5432 \
              ${{secrets.DOCKERHUB_USERNAME}}/${{env.APP_IMAGE_NAME}}:latest
  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Set $author and $author_tg_nick values to env
        run: |
          ghactor=${{github.actor}}
          author=${ghactor,,}
          declare -A tg_nicks=(${{vars.TG_BACK_TEAM_NICKS}})
          if [ ${tg_nicks[$author]+_} ]; then tg_nick="(@${tg_nicks[$author]})"; else tg_nick=""; fi
          echo "AUTHOR=${author}" >> "$GITHUB_ENV"
          echo "AUTHOR_TG_NICK=${tg_nick}" >> "$GITHUB_ENV"
      - name: Send message to Telegram
        run: |-
          tg_chat_id=${{secrets.TG_CHAT_ID}}
          declare -A tg_ids=(${{vars.TG_BACK_TEAM_IDS}})
          if [ ${tg_ids[$AUTHOR]+_} ]; then tg_to="${tg_ids[$AUTHOR]}" extra="";
            else tg_to="-$tg_chat_id" extra="&message_thread_id=${{vars.TG_BACK_THREAD_ID}}"; fi
          message="✨ Hey there!
            Рабочий поток 🐧 ${{github.workflow}} успешно выполнен!
            Событие: 🚀 ${{github.event_name}}
            GitHub автор: 👷 ${{github.actor}} ${{env.AUTHOR_TG_NICK}}
            Репозиторий: 🎉 ${{github.repository}}
            Ветка: 🔎 ${{github.ref_name}}
            Sincerely yours, Xwick Bot ✨"
          curl -s -X POST 'https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage' \
            -d "chat_id=${tg_to}&text=${message}$extra";
