---
name: Flow for individual branches
run-name: ${{ github.actor }} started 🚀 GitHub Actions
on:
  push:
    branches: ['!main', '!develop', '!production', '!review']
    paths-ignore: ['**/pyproject.toml']
  workflow_dispatch:
env:
  POETRY_VERSION: 1.8.2
  PYTHON_VERSION: 3.12
  SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
jobs:
  test:
    name: Linters, Pytest, Pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{env.PYTHON_VERSION}}
      - name: Install and configure Poetry for bot_constructor
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: ./bot_constructor
          version: ${{env.POETRY_VERSION}}
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{runner.os}}-${{env.PYTHON_VERSION}}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: |
          cd bot_constructor/
          poetry install --no-interaction --no-root
      - name: Run bot_constructor local tests
        run: |
          source $VENV
          cd bot_constructor/
          python manage.py test
      - name: Pre-commit global check
        uses: pre-commit/action@v3.0.1
  notify:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set $author and $author_tg_nick values to env
        run: |
          ghactor=${{github.actor}}
          author=${ghactor,,}
          declare -A tg_nicks=(${{vars.TG_BACK_TEAM_NICKS}})
          if [ ${tg_nicks[$author]+_} ]; then tg_nick="(@${tg_nicks[$author]})"; else tg_nick=""; fi
          echo "AUTHOR=${author}" >> "$GITHUB_ENV"
          echo "AUTHOR_TG_NICK=${tg_nick}" >> "$GITHUB_ENV"
      - name: Send message to Telegram
        run: |-
          tg_chat_id=${{secrets.TG_CHAT_ID}}
          declare -A tg_ids=(${{vars.TG_BACK_TEAM_IDS}})
          if [ ${tg_ids[$AUTHOR]+_} ]; then tg_to="${tg_ids[$AUTHOR]}" extra="";
            else tg_to="-$tg_chat_id" extra="&message_thread_id=${{vars.TG_BACK_THREAD_ID}}"; fi
          message="✨ Hey there!
            Рабочий поток 🐧 ${{github.workflow}} успешно выполнен!
            Событие: 🚀 ${{github.event_name}}
            GitHub автор: 👷 ${{github.actor}} ${{env.AUTHOR_TG_NICK}}
            Репозиторий: 🎉 ${{github.repository}}
            Ветка: 🔎 ${{github.ref_name}}
            Sincerely yours, Xwick Bot ✨"
          curl -s -X POST 'https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage' \
            -d "chat_id=${tg_to}&text=${message}$extra";
