---
name: for personal branches
run-name: ${{ github.actor }} started 🚀 GitHub Actions
on:
  push:
    branches-ignore: [main, develop, production, review]
    paths-ignore: ['**/pyproject.toml']
  workflow_dispatch:
jobs:
  test:
    uses: ./.github/workflows/rwf-test-app.yml
    with:
      POETRY_VERSION: 1.8.2
      PYTHON_VERSION: 3.12
      APP_NAME: bot_constructor
  notify:
    uses: ./.github/workflows/rwf-notify.yml
    needs: test
    # secrets: inherit  # pragma: allowlist secret
