---
name: flow for personal branches
run-name: ${{ github.actor }} started 🚀 GitHub Actions
on:
  push:
    branches-ignore: [main, develop, production, review]
    paths-ignore: ['**/pyproject.toml']
  workflow_dispatch:
# env:
#   SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
jobs:
  test_bc:
    uses: ./.github/workflows/rwf-test-bc.yml
    with:
      POETRY_VERSION: 1.8.2
      PYTHON_VERSION: 3.12
    # secrets: inherit
  notify:
    runs-on: ubuntu-latest
    needs: test_bc
    steps:
      - name: Set $author and $author_tg_nick values to env
        run: |
          ghactor=${{github.actor}}
          author=${ghactor,,}
          declare -A tg_nicks=(${{vars.TG_BACK_TEAM_NICKS}})
          if [ ${tg_nicks[$author]+_} ]; then tg_nick="(@${tg_nicks[$author]})"; else tg_nick=""; fi
          echo "AUTHOR=${author}" >> "$GITHUB_ENV"
          echo "AUTHOR_TG_NICK=${tg_nick}" >> "$GITHUB_ENV"
      - name: Send message to Telegram
        run: |-
          tg_chat_id=${{secrets.TG_CHAT_ID}}
          declare -A tg_ids=(${{vars.TG_BACK_TEAM_IDS}})
          if [ ${tg_ids[$AUTHOR]+_} ]; then tg_to="${tg_ids[$AUTHOR]}" extra="";
            else tg_to="-$tg_chat_id" extra="&message_thread_id=${{vars.TG_BACK_THREAD_ID}}"; fi
          message="✨ Hey there!
            Рабочий поток 🐧 ${{github.workflow}} успешно выполнен!
            Событие: 🚀 ${{github.event_name}}
            GitHub автор: 👷 ${{github.actor}} ${{env.AUTHOR_TG_NICK}}
            Репозиторий: 🎉 ${{github.repository}}
            Ветка: 🔎 ${{github.ref_name}}
            Sincerely yours, Xwick Bot ✨"
          curl -s -X POST 'https://api.telegram.org/bot${{secrets.TG_BOT_TOKEN}}/sendMessage' \
            -d "chat_id=${tg_to}&text=${message}$extra";
