---
name: test personal branches
run-name: ${{ github.actor }} started 🚀 GitHub Actions
on:
  push:
    branches-ignore: [main, develop, production, review]
    paths-ignore: ['**/pyproject.toml']
  workflow_dispatch:
jobs:
  test_app:
    if: github.ref_name == 'develop' || github.ref_name == 'production'
    uses: ./.github/workflows/rwf-test-app.yml
    with:
      APP_PROJECT_NAME: bot_constructor
      POETRY_VERSION: ${{vars.PROJECT_POETRY_VERSION}}
      PYTHON_VERSION: ${{vars.PROJECT_PYTHON_VERSION}}
  notify:
    uses: ./.github/workflows/rwf-notify.yml
    needs: test_app
    secrets: inherit  # pragma: allowlist secret
