---
name: Push Docker image to Docker Hub
on:
  workflow_call:
    inputs:
      APP_PROJECT_NAME:
        required: true
        type: string
      APP_IMAGE_NAME:
        required: true
        type: string
      APP_VERSION:
        required: true
        type: string
      DOCKERFILE_NAME:
        required: false
        type: string
        default: Dockerfile
jobs:
  build:
    # if: github.ref_name == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./${{inputs.APP_PROJECT_NAME}}
          file: ${{inputs.APP_PROJECT_NAME}}/${{inputs.DOCKERFILE_NAME}}
          push: true
          tags: |
            ${{secrets.DOCKERHUB_USERNAME}}/${{inputs.APP_IMAGE_NAME}}:latest
            ${{secrets.DOCKERHUB_USERNAME}}/${{inputs.APP_IMAGE_NAME}}:${{inputs.APP_VERSION}}
