---
name: bot_constructor dev stand launch
run-name: ${{ github.actor }} launched 🚀 bot_constructor dev 🚀 stand
on:
  push:
    branches: [develop, feat/samesite-none]
    paths-ignore: ['**/pyproject.toml']
  workflow_dispatch:
env:
  APP_VERSION: dev1.0.1
  APP_PROJECT_NAME: bot_constructor
  APP_IMAGE_NAME: ${{vars.DEV_CONSTRUCTOR_IMAGE_NAME}}
  APP_CONTAINER_NAME: ${{vars.DEV_CONSTRUCTOR_CONTAINER_NAME}}
  APP_DB_NAME: ${{vars.DEV_CONSTRUCTOR_DB_NAME}}
  # APP_DB_USER substituted to APP_DB_NAME
  APP_DB_USER: ${{vars.DEV_CONSTRUCTOR_DB_NAME}}
  APP_DB_PWD: ${{vars.DEV_CONSTRUCTOR_DB_PWD}}
  APP_VOLUME: dev_constructor
  BOT_SERVER_URL: ${{vars.BOT_SERVER_URL}}
jobs:
  variables:
    name: Pass env variables to rwf
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{env.APP_VERSION}}
      app_project_name: ${{env.APP_PROJECT_NAME}}
      app_image_name: ${{env.APP_IMAGE_NAME}}
      app_container_name: ${{env.APP_CONTAINER_NAME}}
      app_db_name: ${{env.APP_DB_NAME}}
      app_db_user: ${{env.APP_DB_USER}}
      app_db_pwd: ${{env.APP_DB_PWD}}
      app_volume: ${{env.APP_VOLUME}}
      bot_server_url: ${{env.BOT_SERVER_URL}}
    steps:
      - name: Echo - fake step
        if: false
        run: echo

  build-bc:
    needs: variables
    uses: ./.github/workflows/rwf-build.yml
    with:
      APP_PROJECT_NAME: ${{needs.variables.outputs.app_project_name}}
      APP_IMAGE_NAME: ${{needs.variables.outputs.app_image_name}}
      APP_VERSION: ${{needs.variables.outputs.app_version}}
    secrets: inherit  # pragma: allowlist secret

  deploy-dc:
    needs: [variables, build-bc]
    uses: ./.github/workflows/rwf-deploy.yml
    with:
      APP_IMAGE_NAME: ${{needs.variables.outputs.app_image_name}}
      APP_CONTAINER_NAME: ${{needs.variables.outputs.app_container_name}}
      APP_DB_NAME: ${{needs.variables.outputs.app_db_name}}
      APP_DB_USER: ${{needs.variables.outputs.app_db_user}}
      APP_DB_PWD: ${{needs.variables.outputs.app_db_pwd}}
      APP_VOLUME: ${{needs.variables.outputs.app_volume}}
      BOT_SERVER_URL: ${{needs.variables.outputs.bot_server_url}}
    secrets: inherit  # pragma: allowlist secret

  notify:
    uses: ./.github/workflows/rwf-notify.yml
    needs: deploy-dc
    secrets: inherit  # pragma: allowlist secret
