---
name: modular bot_constructor CICD
run-name: ${{ github.actor }} started 🚀 GitHub Actions
on:
  push:
    branches: [production, develop, feat/container-for-bot-server]
    paths-ignore: ['**/pyproject.toml']
  workflow_dispatch:
env:
  APP_VERSION: 0.0.1
  APP_PROJECT_NAME: bot_constructor
  APP_IMAGE_NAME: ${{vars.BOT_CONSTRUCTOR_IMAGE_NAME}}
  APP_CONTAINER_NAME: ${{vars.BOT_CONSTRUCTOR_CONTAINER_NAME}}
#   SECRET_KEY: ${{secrets.DJANGO_SECRET_KEY}}
jobs:
  env:
    runs-on: ubuntu-latest
    outputs:
      APP_PROJECT_NAME: ${{steps.data.outputs.APP_PROJECT_NAME}}
    steps:
      - name: Print inputs passed to the reusable workflow
        id: data
        run: |
          echo "apn: $APP_PROJECT_NAME"
          echo "APP_PROJECT_NAME=$APP_PROJECT_NAME" >> $GITHUB_OUTPUT

  lint:
    uses: ./.github/workflows/rwf-precommit.yml
    with:
      PYTHON_VERSION: ${{vars.PROJECT_PYTHON_VERSION}}

  test-bc:
    needs: lint
    uses: ./.github/workflows/rwf-pytest.yml
    with:
      APP_PROJECT_NAME: ${{ needs.env.outputs.APP_PROJECT_NAME }}
      POETRY_VERSION: ${{vars.PROJECT_POETRY_VERSION}}
      PYTHON_VERSION: ${{vars.PROJECT_PYTHON_VERSION}}

  # build:
  #   needs: test-bc
  #   uses: ./.github/workflows/rwf-deploy.yml
  #   with:
  #     APP_PROJECT_NAME: ${{env.APP_PROJECT_NAME}}
  #   secrets: inherit  # pragma: allowlist secret


  # deploy:
  #   name: Deployment on remote server
  #   if: github.ref_name == 'develop'
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: executing remote ssh commands
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{secrets.MODULAR_HOST}}
  #         username: ${{secrets.HOST_USER}}
  #         key: ${{secrets.HOST_SSH_KEY}}
  #         script: |
  #           docker stop ${{env.APP_CONTAINER_NAME}}
  #           docker rm ${{env.APP_CONTAINER_NAME}}
  #           docker rmi ${{secrets.DOCKERHUB_USERNAME}}/${{env.APP_IMAGE_NAME}}:latest
  #           docker pull ${{secrets.DOCKERHUB_USERNAME}}/${{env.APP_IMAGE_NAME}}:latest
  #           docker run -d \
  #             --name=${{env.APP_CONTAINER_NAME}} \
  #             --hostname=${{env.APP_CONTAINER_NAME}} \
  #             --net=${{secrets.MODULAR_NETWORK_NAME}} \
  #             --restart=unless-stopped \
  #             -e DEBUG=FALSE \
  #             -e DJANGO_SUPERUSER_USERNAME=${{secrets.DJANGO_SUPERUSER_USERNAME}} \
  #             -e DJANGO_SUPERUSER_PASSWORD=${{secrets.DJANGO_SUPERUSER_PASSWORD}} \
  #             -e DJANGO_SUPERUSER_EMAIL=${{secrets.DJANGO_SUPERUSER_EMAIL}} \
  #             -e ALLOWED_HOSTS=${{secrets.DJANGO_ALLOWED_HOSTS}} \
  #             -e CSRF_TRUSTED_ORIGINS=${{secrets.DJANGO_CSRF_TRUSTED_ORIGINS}} \
  #             -e POSTGRES_DB=${{secrets.DJANGO_DB_NAME}} \
  #             -e POSTGRES_USER=${{secrets.DJANGO_POSTGRES_USER}} \
  #             -e POSTGRES_PASSWORD=${{secrets.DJANGO_POSTGRES_PASSWORD}} \
  #             -e DB_HOST='postgres' \
  #             -e DB_PORT=5432 \
  #             -v bot_static:/app/bot_constructor/static/ \
  #             -v bot_media:/app/bot_constructor/media/ \
  #             ${{secrets.DOCKERHUB_USERNAME}}/${{env.APP_IMAGE_NAME}}:latest
  notify:
    uses: ./.github/workflows/rwf-notify.yml
    needs: test-bc
    secrets: inherit  # pragma: allowlist secret
